# Generated by Django 3.2.6 on 2022-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
